service: deployable-lambda

provider:
  name: aws
  runtime: python3.7
  stage: $(opt:stage, 'dev')
  region: us-east-2

package:
  exclude:
    - .venv/**
    - .git/**
    - __pycache__/**
    - node_modules/**

functions:
  hello_world:
    handler: handler.call

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux